import {
  Lightbulb,
  Trophy,
  GraduationCap,
  TrendingUp,
  Code2,
  Smartphone,
  Sparkles,
} from "lucide-react";

export const WHY = [
  {
    icon: Lightbulb,
    title: "Innovation First",
    desc: "Work on cutting-edge problems and build products that actually make a difference.",
  },
  {
    icon: Trophy,
    title: "Ownership",
    desc: "Take charge of your modules and projects. We value outcomes over hours.",
  },
  {
    icon: GraduationCap,
    title: "Learning Culture",
    desc: "A fast-paced startup environment where you learn more in 3 months than 3 years elsewhere.",
  },
  {
    icon: TrendingUp,
    title: "Accelerated Growth",
    desc: "As the company scales, so does your career path and responsibility.",
  },
];

export const ROLES = [
  {
    title: "React Developer Intern",
    location: "Remote / Bhavnagar",
    type: "Internship",
    desc: "Help build and scale our modern digital platforms using Next.js, React and advanced UI frameworks.",
    icon: Code2,
    bgClass: "bg-copper-light",
    borderClass: "border-copper/15",
    textClass: "text-foreground",
    descClass: "text-muted-foreground",
    badgeClass: "bg-copper/5 border-copper/20 text-copper",
    metaClass: "text-muted-foreground",
    iconBgClass: "bg-white border-copper/10 text-copper",
    buttonBgClass: "bg-neutral-900 text-white hover:bg-copper",
    innerBgClass: "bg-copper-light",
  },
  {
    title: "Flutter Developer Intern",
    location: "Remote / Bhavnagar",
    type: "Internship",
    desc: "Work on mobile-first operational tools and cross-platform applications for global industries.",
    icon: Smartphone,
    bgClass: "bg-surface",
    borderClass: "border-border/60",
    textClass: "text-foreground",
    descClass: "text-muted-foreground",
    badgeClass: "bg-copper/5 border-copper/20 text-copper",
    metaClass: "text-muted-foreground",
    iconBgClass: "bg-copper/5 border-copper/15 text-copper",
    buttonBgClass: "bg-neutral-900 text-white hover:bg-copper",
    innerBgClass: "bg-surface",
  },
  {
    title: "Sales Intern",
    location: "Field / Remote",
    type: "Internship",
    desc: "Identify market opportunities and assist in strategic lead generation for DZ Infotech's product suite.",
    icon: TrendingUp,
    bgClass: "bg-neutral-900",
    borderClass: "border-neutral-800",
    textClass: "text-white",
    descClass: "text-neutral-400",
    badgeClass: "bg-white/10 border-white/20 text-white",
    metaClass: "text-neutral-400",
    iconBgClass: "bg-white/10 border-white/10 text-white",
    buttonBgClass: "bg-white text-neutral-900 hover:bg-copper hover:text-white",
    innerBgClass: "bg-neutral-900",
  },
  {
    title: "Marketing / Digital Marketing Intern",
    location: "Remote",
    type: "Internship",
    desc: "Create high-impact digital content and manage campaigns for a visionary technology brand.",
    icon: Sparkles,
    bgClass: "bg-gray-100",
    borderClass: "border-gray-200",
    textClass: "text-foreground",
    descClass: "text-muted-foreground",
    badgeClass: "bg-copper/5 border-copper/20 text-copper",
    metaClass: "text-muted-foreground",
    iconBgClass: "bg-white border-gray-300 text-foreground",
    buttonBgClass: "bg-neutral-900 text-white hover:bg-copper",
    innerBgClass: "bg-gray-100",
  },
];

export const POSITIONS = [...ROLES.map((r) => r.title), "Open Application"];
